### ISSUE TITLE
Crash when trying to launch campaign

### ISSUE THREAD

**Issue by hamstah** [gophish/gophish#118]
Hi,

See stacktrace, I haven't included all the other goroutine, let me know if useful.

Steps to reproduce
- Do not change the stmp settings in config.json
- Create a template
- Create a page
- Create a group
- Create campaign and select the template/page/group
- Click launch campaign

```
xx.xx.xxx.xxx - - [02/Feb/2016:15:19:50 +0000] "POST /api/campaigns/?api_key=xxx HTTP/1.1" 400 74 "https://xxxx/campaigns" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
 2016/02/02 15:20:01 main_private.go:23: sql/root/projects/src/github.com/gophish/gophish/models/campaign.go:1001.603322msINSERT INTO "events" ("message","campaign_id","email","time") VALUES (?,?,?,?) [Campaign Created 1  2016-02-02 15:20:01.997119239 +0000 UTC]
 2016/02/02 15:20:02 worker.go:42: Worker received: Test
xx.xx.xxx.xxx - - [02/Feb/2016:15:20:01 +0000] "POST /api/campaigns/?api_key=xxx HTTP/1.1" 201 29464 "https://xxx/campaigns" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
 2016/02/02 15:20:02 worker.go:57: mail: no address
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x647c32]
goroutine 8 [running]:
github.com/gophish/gophish/worker.processCampaign(0xc820254d20)
        /root/projects/src/github.com/gophish/gophish/worker/worker.go:59 +0x26a2
github.com/gophish/gophish/worker.(*Worker).Start(0xc82002ab98)
        /root/projects/src/github.com/gophish/gophish/worker/worker.go:37 +0x119
created by github.com/gophish/gophish/controllers.init.1
        /root/projects/src/github.com/gophish/gophish/controllers/api.go:28 +0x9f

```

**Comment by jordan-wright** [comment]
Make sure to set a "from" address in the expanded SMTP setting in the campaign launch modal.

This has been fixed in the master branch and will be in the next release :)

**Comment by hamstah** [comment]
Cool, I suspected it was due to me ignoring the SMTP options.
Thanks for the quick reply.
