### ISSUE TITLE
Crash when no SMTP settings applied when starting a Campaign

### ISSUE THREAD

**Issue by mubix** [gophish/gophish#133]
When I started gophish back up it said the campaign was underway

```
 2016/02/06 04:27:37 worker.go:42: Worker received: Ubertest
 2016/02/06 04:27:37 worker.go:57: mail: no address
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x647c32]

goroutine 8 [running]:
github.com/gophish/gophish/worker.processCampaign(0xc82012b4a0)
	/root/projects/src/github.com/gophish/gophish/worker/worker.go:59 +0x26a2
github.com/gophish/gophish/worker.(*Worker).Start(0xc820026b98)
	/root/projects/src/github.com/gophish/gophish/worker/worker.go:37 +0x119
created by github.com/gophish/gophish/controllers.init.1
	/root/projects/src/github.com/gophish/gophish/controllers/api.go:28 +0x9f

goroutine 1 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc82019687c)
	/root/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc820196870)
	/root/go/src/sync/waitgroup.go:126 +0xb4
main.main()
	/root/projects/src/github.com/gophish/gophish/gophish.go:75 +0x17b

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 58 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f462ba58d58, 0x72, 0xc82000a1c0)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8206ba990, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8206ba990, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8206ba930, 0xc820257000, 0x1000, 0x1000, 0x0, 0x7f462ba4f050, 0xc82000a1c0)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200263e0, 0xc820257000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc820328d58, 0xc820257000, 0x1000, 0x1000, 0x40b201, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82060fe20, 0xc820257000, 0x1000, 0x1000, 0xc820001b00, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc8205f4a80)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8205f4a80, 0xc81ffc890a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc8205f4a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc8204f7fb0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc8204f7fb0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc8205f4a80, 0xc8206ecd20, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc820328d10, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc820328d10)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 59 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f462ba58e18, 0x72, 0xc82000a1c0)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8206baa00, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8206baa00, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8206ba9a0, 0xc820251000, 0x1000, 0x1000, 0x0, 0x7f462ba4f050, 0xc82000a1c0)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200263e8, 0xc820251000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc820328f68, 0xc820251000, 0x1000, 0x1000, 0x40b201, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82060fe80, 0xc820251000, 0x1000, 0x1000, 0xc820001c80, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc8205f4ae0)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8205f4ae0, 0xc81ffc890a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc8205f4ae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc82071be90, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc82071be90, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc8205f4ae0, 0xc8206ecc40, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc820328f20, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc820328f20)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7f462ba58ed8, 0x72, 0xc82000a1c0)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820248ca0, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820248ca0, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820248c40, 0xc820201000, 0x1000, 0x1000, 0x0, 0x7f462ba4f050, 0xc82000a1c0)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026d68, 0xc820201000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc8201db178, 0xc820201000, 0x1000, 0x1000, 0xc820250000, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82022cb80, 0xc820201000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820215920)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820215920, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:132 +0xcc
net/http.(*conn).readRequest(0xc8201db130, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:629 +0x2bb
net/http.(*conn).serve(0xc8201db130)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 9 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc8201b57c0)
	/root/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/root/go/src/database/sql/sql.go:481 +0x336

goroutine 10 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f462ba58f98, 0x72, 0xc82000a1c0)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820248c30, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820248c30, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820248bd0, 0x0, 0x7f462ba59150, 0xc820634020)
	/root/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026d60, 0x458ee0, 0x0, 0x0)
	/root/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820026d60, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8202158c0, 0x7f462ba59118, 0xc820026d60, 0x0, 0x0)
	/root/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8202158c0, 0x0, 0x0)
	/root/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82000af10, 0xe, 0x7f462ba58080, 0xc82022cac0, 0x0, 0x0)
	/root/go/src/net/http/server.go:1967 +0x8f
main.main.func1(0xc820196870)
	/root/projects/src/github.com/gophish/gophish/gophish.go:60 +0x671
created by main.main
	/root/projects/src/github.com/gophish/gophish/gophish.go:62 +0x134

goroutine 11 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f462ba59058, 0x72, 0xc82000a1c0)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820206990, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820206990, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820206930, 0x0, 0x7f462ba59150, 0xc820192dc0)
	/root/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026c10, 0xc820047c88, 0x0, 0x0)
	/root/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820026c10, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820169b60, 0x7f462ba59118, 0xc820026c10, 0x0, 0x0)
	/root/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820169b60, 0x0, 0x0)
	/root/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82000b000, 0xa, 0x7f462ba58080, 0xc820192da0, 0x0, 0x0)
	/root/go/src/net/http/server.go:1967 +0x8f
main.main.func2(0xc820196870)
	/root/projects/src/github.com/gophish/gophish/gophish.go:72 +0x67d
created by main.main
	/root/projects/src/github.com/gophish/gophish/gophish.go:74 +0x16d

goroutine 15 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f462ba58c98, 0x72, 0xc82000a1c0)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820248df0, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820248df0, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820248d90, 0xc820255000, 0x1000, 0x1000, 0x0, 0x7f462ba4f050, 0xc82000a1c0)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026d80, 0xc820255000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc8201db598, 0xc820255000, 0x1000, 0x1000, 0x40b201, 0x0, 0x0)
	/root/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc82022cce0, 0xc820255000, 0x1000, 0x1000, 0xc8201fe900, 0x0, 0x0)
	/root/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820215a40)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820215a40, 0xc81ffc890a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820215a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc82071bec0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc82071bec0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820215a40, 0xc8206eca80, 0x0, 0x0)
	/root/go/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8201db550, 0x0, 0x0, 0x0)
	/root/go/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8201db550)
	/root/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/root/go/src/net/http/server.go:1910 +0x3f6

goroutine 47 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f462ba58998, 0x72, 0xc82000a1c0)
	/root/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82015daa0, 0x72, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82015daa0, 0x0, 0x0)
	/root/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82015da40, 0xc8200ec000, 0x1000, 0x1000, 0x0, 0x7f462ba4f050, 0xc82000a1c0)
	/root/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026778, 0xc8200ec000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f462ba59288, 0xc820026778, 0xc82061a3c8, 0xc8200ec000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/root/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8204f9420, 0xc8200ec000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8200186c0)
	/root/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200186c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82061a370)
	/root/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/root/go/src/net/http/transport.go:685 +0xc78

goroutine 48 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc82061a370)
	/root/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/root/go/src/net/http/transport.go:686 +0xc9d
root@testbox1:/opt/gophish/gophish_linux_amd64# channel 7: open failed: connect failed: Connection refused

```

**Comment by jordan-wright** [comment]
Hey Rob,

Yep! Unfortunately this was a bug that resulted from not specifying a "From" address. I believe this is already patched in master, so the next release won't have this problem.

Thanks for the report! Btw - huge fan. Keep up the awesome work you do.

**Comment by jordan-wright** [comment]
Hey Rob,

I tracked down the commit - https://github.com/gophish/gophish/commit/bf86356fde8d860ec3515709200452fb1bc08cfd

Looks like we're slated for the next release, but if you build from source you'll be good to go now.

**Comment by mubix** [comment]
sweet! thanks
