### ISSUE TITLE
Added User / Login leads to an incorrect redirect after login

### ISSUE THREAD

**Issue by H4xl0r** [gophish/gophish#1469]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 
20190105192341
with added fixes : 
#1451 #1448 #1400 

Brief description of the issue: 

Added user via webinterface (as admin)
login as new user 
redirect crashes / connection error / infos  in terminal below

What are you expecting to see happen? :
Login with other premissions or even login to normal dashboard (admin)

What are you seeing happen?

error about the role_id , new user gots role_id 0 (needs to be 1or2)
changing role_id to 1 fixes the problem (gets admin and is able to login)
changing role_id to 2 fixes the problem (still gets admin and is bale to login and edit stuff !)

but thats more a workaround there are roles for users , why are they not working ?
 
like the login checking for the user and adds the role_id to the session.
menu then checking for user role_id and give specific menus (user role_id 2 should not be able to see/get to system settings / etc.)

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html
Insert code here
```

Please provide any terminal output that may be relevant below:

```
2019/05/30 16:09:15 http2: panic serving 192.168.1.24:63952: runtime error: invalid memory address or nil pointer dereference
goroutine 1505 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0007694f8, 0xc0008bdfaf, 0xc0006bc380)
	/usr/lib/go-1.11/src/net/http/h2_bundle.go:5870 +0x17c
panic(0xa91260, 0x10092d0)
	/usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
github.com/jinzhu/gorm.(*Scope).related(0x0, 0xa3c000, 0xc00071a9a0, 0xc0006189d0, 0x1, 0x1, 0x1)
	/root/go/src/github.com/jinzhu/gorm/scope.go:1069 +0x3a
github.com/jinzhu/gorm.(*Association).Find(0xc000612cf0, 0xa3c000, 0xc00071a9a0, 0xc000612cf0)
	/root/go/src/github.com/jinzhu/gorm/association.go:19 +0x8f
github.com/gophish/gophish/models.(*User).HasPermission(0xc0008bcf38, 0xb38065, 0xd, 0xaef080, 0xc0002381b0, 0x78e385)
	/root/go/src/github.com/gophish/gophish/models/rbac.go:78 +0x1e7
github.com/gophish/gophish/controllers.newTemplateParams(0xc0000eca00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/gophish/gophish/controllers/route.go:154 +0x117
github.com/gophish/gophish/controllers.(*AdminServer).Base(0xc0001bbef0, 0xbe7180, 0xc0000ca0e0, 0xc0000eca00)
	/root/go/src/github.com/gophish/gophish/controllers/route.go:201 +0x43
github.com/gophish/gophish/controllers.(*AdminServer).Base-fm(0xbe7180, 0xc0000ca0e0, 0xc0000eca00)
	/root/go/src/github.com/gophish/gophish/controllers/route.go:98 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0004d40d0, 0xbe7180, 0xc0000ca0e0, 0xc0000eca00)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
github.com/gophish/gophish/middleware.RequireLogin.func1(0xbe7180, 0xc0000ca0e0, 0xc0000eca00)
	/root/go/src/github.com/gophish/gophish/middleware/middleware.go:109 +0xad
net/http.HandlerFunc.ServeHTTP(0xc0001cd340, 0xbe7180, 0xc0000ca0e0, 0xc0000eca00)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000ee6c0, 0xbe7180, 0xc0000ca0e0, 0xc0000ec800)
	/root/go/src/github.com/gorilla/mux/mux.go:212 +0xd0
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc000516500, 0xbe7180, 0xc0000ca0e0, 0xc0000ec700)
	/root/go/src/github.com/gorilla/csrf/csrf.go:267 +0x320
net/http.Handler.ServeHTTP-fm(0xbe7180, 0xc0000ca0e0, 0xc0000ec600)
	/root/go/src/github.com/gophish/gophish/controllers/route.go:121 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc000502820, 0xbe7180, 0xc0000ca0e0, 0xc0000ec600)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
github.com/gophish/gophish/middleware.CSRFExceptions.func1(0xbe7180, 0xc0000ca0e0, 0xc0000ec600)
	/root/go/src/github.com/gophish/gophish/middleware/middleware.go:30 +0xa7
net/http.HandlerFunc.ServeHTTP(0xc000502840, 0xbe7180, 0xc0000ca0e0, 0xc0000ec600)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
github.com/gophish/gophish/middleware.GetContext.func1(0xbe7180, 0xc0000ca0e0, 0xc0000ec500)
	/root/go/src/github.com/gophish/gophish/middleware/middleware.go:60 +0x255
net/http.HandlerFunc.ServeHTTP(0xc000502860, 0xbe7180, 0xc0000ca0e0, 0xc0000ec400)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x7fe5884a1cc0, 0xc00071a320, 0xc0000ec400)
	/root/go/src/github.com/NYTimes/gziphandler/gzip.go:336 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc0004d1dd0, 0x7fe5884a1cc0, 0xc00071a320, 0xc0000ec400)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xbe2240, 0xc00009f5d0, 0xbe3140, 0xc0004d1dd0, 0xb5d888, 0xbe6fc0, 0xc0007694f8, 0xc0000ec400)
	/root/go/src/github.com/gorilla/handlers/logging.go:45 +0x133
net/http.serverHandler.ServeHTTP(0xc000123a00, 0xbe6fc0, 0xc0007694f8, 0xc0000ec400)
	/usr/lib/go-1.11/src/net/http/server.go:2741 +0xab
net/http.initNPNRequest.ServeHTTP(0xc000079c00, 0xc000123a00, 0xbe6fc0, 0xc0007694f8, 0xc0000ec400)
	/usr/lib/go-1.11/src/net/http/server.go:3291 +0x8d
net/http.Handler.ServeHTTP-fm(0xbe6fc0, 0xc0007694f8, 0xc0000ec400)
	/root/go/src/github.com/gophish/gophish/controllers/route.go:121 +0x4d
net/http.(*http2serverConn).runHandler(0xc0006bc380, 0xc0007694f8, 0xc0000ec400, 0xc00071a120)
	/usr/lib/go-1.11/src/net/http/h2_bundle.go:5877 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/lib/go-1.11/src/net/http/h2_bundle.go:5611 +0x4d3


```

Please provide as many steps as you can to reproduce the problem:
Added user via webinterface (as admin)
login as new user 
redirect crashes / connection error / infos  in terminal below

**Comment by H4xl0r** [comment]
@jordan-wright please give me some info how to contact you, would like to get in touch with you !

**Comment by H4xl0r** [comment]
`func Register(r *http.Request) (bool, error) {
	username := r.FormValue("username")
	newPassword := r.FormValue("password")
	confirmPassword := r.FormValue("confirm_password")
	u, err := models.GetUserByUsername(username)
	// If the given username already exists, throw an error and return false
	if err == nil {
		return false, ErrUsernameTaken
	}

	// If we have an error which is not simply indicating that no user was found, report it
	if err != nil && err != gorm.ErrRecordNotFound {
		log.Warn(err)
		return false, err
	}

	u = models.User{}
	// If we've made it here, we should have a valid username given
	// Check that the passsword isn't blank
	if newPassword == "" {
		return false, ErrEmptyPassword
	}
	// Make sure passwords match
	if newPassword != confirmPassword {
		return false, ErrPasswordMismatch
	}
	// Let's create the password hash
	h, err := bcrypt.GenerateFromPassword([]byte(newPassword), bcrypt.DefaultCost)
	if err != nil {
		return false, err
	}
	u.Username = username
	u.Hash = string(h)
	u.ApiKey = GenerateSecureKey()
	err = models.PutUser(&u)
	return true, nil
}`

i think there needs to be a change adding the role_id 2 (default would be 1 admin and 2 user)

**Comment by H4xl0r** [comment]
Suggestions:
1 Fix the new user problem (if adding a new user Newusertemplate should ask for admin or user and set role_id to 1or 2 as specified ).

2 Add the parameter to the login process (request and encrypt the role_id of the user like the other infos and give it to the browser / session )

3Add role_id request in the menu part to show specific menus ( if user_role 2 menu->settings hide / etc ).

Let me know how i can support you

**Comment by H4xl0r** [comment]
dublicate #1375
