### ISSUE TITLE
Unexplainable crashes. Possibly MySQL related.

### ISSUE THREAD

**Issue by dennisbaaten** [gophish/gophish#2242]
I'm using Gophish v0.11.0 on a dedicated VPS running Linux Debian 10 (Buster). I hooked it up to a MariaDB database and I'm using a local Postfix for sending mails. I run gophish using screen.

Today I started a campaign with 6954 users. Unfortunately gophish crashed two times, affecting the results of my campaign since URL's in the phishing mail result in a 404 error. In an attempt to find out what happened, I started digging in logs. 

The stdout in the screen session showed multiple errors like this: 
```
goroutine 189796 [IO wait]:
internal/poll.runtime_pollWait(0x7fddfb30f2e0, 0x72, 0xffffffffffffffff)
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc016844798, 0x72, 0x200, 0x205, 0xffffffffffffffff)
        /opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc016844780, 0xc00c8a86c0, 0x205, 0x205, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.7/x64/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc016844780, 0xc00c8a86c0, 0x205, 0x205, 0x203006, 0x0, 0x417cdb)
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc016756a28, 0xc00c8a86c0, 0x205, 0x205, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc01842f600, 0xc00c8a86c0, 0x205, 0x205, 0x61d164, 0xc00338cb40, 0xc01da90cf0)
        /opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc00ed0b3d8, 0xce6ce0, 0xc01842f600, 0x418dd5, 0xb41660, 0xbc01c0)
        /opt/hostedtoolcache/go/1.14.7/x64/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00ed0b180, 0xce7a40, 0xc016756a28, 0x5, 0xc016756a28, 0x6f574d)
        /opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00ed0b180, 0x0, 0x0, 0xc01da90f60)
        /opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
        /opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00ed0b180, 0xc01b83f661, 0x1, 0x1, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.7/x64/src/crypto/tls/conn.go:1233 +0x15b
net/http.(*connReader).backgroundRead(0xc01b83f650)
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:689 +0x58
created by net/http.(*connReader).startBackgroundRead
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:685 +0xd0

goroutine 189799 [select]:
database/sql.(*DB).conn(0xc0000d83c0, 0xcf6b00, 0xc000024098, 0xc0122e0f01, 0xc003dfd888, 0x410bba, 0xafe920)
        /opt/hostedtoolcache/go/1.14.7/x64/src/database/sql/sql.go:1184 +0x7ac
database/sql.(*DB).query(0xc0000d83c0, 0xcf6b00, 0xc000024098, 0xc0122e0f50, 0x4b, 0xc01d8e7c50, 0x1, 0x1, 0x1477901, 0x0, ...)
        /opt/hostedtoolcache/go/1.14.7/x64/src/database/sql/sql.go:1552 +0x66
database/sql.(*DB).QueryContext(0xc0000d83c0, 0xcf6b00, 0xc000024098, 0xc0122e0f50, 0x4b, 0xc01d8e7c50, 0x1, 0x1, 0xc01d8e7c00, 0xbf4e3d, ...)
        /opt/hostedtoolcache/go/1.14.7/x64/src/database/sql/sql.go:1534 +0xd1
database/sql.(*DB).Query(0xc0000d83c0, 0xc0122e0f50, 0x4b, 0xc01d8e7c50, 0x1, 0x1, 0x0, 0x1, 0x41ae86)
        /opt/hostedtoolcache/go/1.14.7/x64/src/database/sql/sql.go:1548 +0x82
github.com/jinzhu/gorm.queryCallback(0xc01d3cb680)
        /home/runner/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/callback_query.go:72 +0x37d
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc01d3cb680, 0xc000186660, 0x3, 0x4, 0x0)
        /home/runner/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/scope.go:869 +0x83
github.com/jinzhu/gorm.(*DB).First(0xc0136631e0, 0xba27a0, 0xc013663110, 0x0, 0x0, 0x0, 0xc0136631e0)
        /home/runner/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/main.go:334 +0x121
github.com/gophish/gophish/models.GetResult(0xc00325566a, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/gophish/gophish/models/result.go:208 +0x11e
github.com/gophish/gophish/controllers.setupContext(0xc01b878700, 0x120, 0xc013c02d80, 0x7fde1c368e58)
        /home/runner/work/gophish/gophish/controllers/phish.go:344 +0x382
github.com/gophish/gophish/controllers.(*PhishingServer).PhishHandler(0xc000233900, 0x7fde1ec66c08, 0xc01162a9c0, 0xc01b878700)
        /home/runner/work/gophish/gophish/controllers/phish.go:199 +0x43
net/http.HandlerFunc.ServeHTTP(0xc000247a40, 0x7fde1ec66c08, 0xc01162a9c0, 0xc01b878700)
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d8840, 0x7fde1ec66c08, 0xc01162a9c0, 0xc00f1a8400)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x7fde1ec66c08, 0xc01162a9c0, 0xc00f1a8400)
        /home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:342 +0x2f1
net/http.HandlerFunc.ServeHTTP(0xc0002928a0, 0x7fde1ec66c08, 0xc01162a9c0, 0xc00f1a8400)
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2041 +0x44
github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xce7820, 0xc000011a78, 0xce8880, 0xc0002928a0, 0xc1f228, 0xcf4900, 0xc00e5bd960, 0xc00f1a8400)
        /home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.4.2/logging.go:45 +0x243
net/http.serverHandler.ServeHTTP(0xc00024a0e0, 0xcf4900, 0xc00e5bd960, 0xc00f1a8400)
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc00d4a9c20, 0xcf6ac0, 0xc00168f6c0)
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2962 +0x35c
```

I am able to start gophish again, and the **gophish.log** states the following.
```
time="2021-06-21T13:57:44+02:00" level=info msg="REDACTED-IP - - [21/Jun/2021:13:57:43 +0200] \"GET /?rid=WgLPr7X HTTP/1.1\" 200 10850 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36\""
time="2021-06-21T14:40:19+02:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"

time="2021-06-21T22:07:58+02:00" level=info msg="REDACTED-IP - - [21/Jun/2021:22:07:45 +0200] \"GET /?rid=4fuLfAa HTTP/1.1\" 200 3924 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Safari/537.36\""
time="2021-06-21T23:09:47+02:00" level=info msg="Background Worker Started Successfully - Waiting for Campaigns"
```
This does actually does not show anything usefull, except the last request that was processed, and the time at which I discovered gophish to be offline and restarted it: 45 minutes the first time and 60 minutes the second time.

The mysql/error.log shows:
```
2021-06-21 13:58:18 192 [Warning] Aborted connection 192 to db: 'gophish' user: 'gophishuser' host: 'localhost' (Got an error reading communication packets)
2021-06-21 22:08:15 388 [Warning] Aborted connection 388 to db: 'gophish' user: 'gophishuser' host: 'localhost' (Got an error reading communication packets)
```
 
So at this moment my best guess is to change some MariaDB variables in order to prevent gophish from crashing:
```
max_connections = 400 (default: 151) 
max allowed packet = 268.435.456 (256M instead of default 16M) 
```

Any other thoughs or tips regarding this issue? 
FYI: I used gophish before running campaigns with approx 1000 and 2600 users and never experienced this problem before.

**Comment by glennzw** [comment]
Gosh this is a hard one to figure out, but given the `gorm` references in the output I think you're right about it possibly being a database issue. Could you share your `config.json`.

I've never used gophish with MariaDB, and whilst it should be pretty much the same as MySQL there might be some idiosyncrasies creeping in. Would you be able to run your test again with MySQL ?

**Comment by dennisbaaten** [comment]
I'm unfortunately not able to run the test again with MySQL. After changing the aforementioned MariaDB variables the crashes did not occur again, but I find it difficult jumping to conclusions since I don't know what actually caused the crashes. I can only make an educated guess based on the information in my logs.

My config.json:
```
{
        "admin_server": {
                "listen_url": "REDACTED:3333",
                "use_tls": true,
                "cert_path": "cert.pem",
                "key_path": "privkey.pem"
        },
        "phish_server": {
                "listen_url": "REDACTED:443",
                "use_tls": true,
                "cert_path": "cert.pem",
                "key_path": "privkey.pem"
        },
        "db_name": "mysql",
        "db_path": "gophishuser:REDACTED@(localhost:3306)/gophish?charset=utf8&parseTime=True&loc=UTC",
        "migrations_prefix": "db/db_",
        "contact_address": "dennis@REDACTED",
        "logging": {
                "filename": "gophish.log",
                "level": "debug"
        }
}
```

**Comment by glennzw** [comment]
OK I can't think of what else we can do; I've never had trouble with MySQL with >20k users, so perhaps those variables you changed were the secret when using MariaDB.

**Comment by dennisbaaten** [comment]
Ok. Thanks for the input. I'm closing this ticket for now.
