### ISSUE TITLE
Python APi not working with POST 

### ISSUE THREAD

**Issue by paulecs2** [gophish/gophish#3141]
**Thanks for reaching out! We're happy to help resolve issues as quickly as possible.**

**Please use this template when creating a new issue. If you do not follow this template format, your issue may be closed without comment.**

Before filing a new issue, please use the search bar at the top of the browser to search for similar issues. Also, please make sure you have read our [documentation](https://getgophish.com/documentation/), which covers how to use Gophish.

What version of Gophish are you using?: 0.12.1

Brief description of the issue: Python API not working with post , but the get request are working fine 

What are you expecting to see happen? :
The groups i have just hsould be post to my GoPhish server

What are you seeing happen?

Traceback (most recent call last):
  File "/var/www/html/test.py", line 45, in <module>
    group = api.groups.post(group)
  File "/home/cytech/.local/lib/python2.7/site-packages/gophish/api/groups.py", line 15, in post
    return super(API, self).post(group)
  File "/home/cytech/.local/lib/python2.7/site-packages/gophish/api/api.py", line 106, in post
    raise Error.parse(response.json())
  File "/home/cytech/.local/lib/python2.7/site-packages/gophish/models.py", line 490, in parse
    error = cls()
  File "/home/cytech/.local/lib/python2.7/site-packages/gophish/models.py", line 480, in __init__
    super().__init__(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

Please provide any terminal output that may be relevant below:

```
time="2024-04-16T16:40:44+02:00" level=error msg="record not found"
time="2024-04-16T16:40:44+02:00" level=info msg="127.0.0.1 - - [16/Apr/2024:16:40:44 +0200] \"POST /api/groups/ HTTP/1.1\" 400 75 \"\" \"python-requests/2.24.0\""
```

Please provide as many steps as you can to reproduce the problem:
 * Step 1 - Python is v2.7.18
 * Step 2 - 
 * Heres the simple code that i use, it's the same than from Python API Documentation  :
 * ```targets = [
    User(
        first_name='John',
        last_name='Doe',
        email='foo@example.com',
        position='Systems Administrator'
    )
]

group=Group(name="test",target=targets)

group = api.groups.post(group)
print (group.id)```

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)
