### ISSUE TITLE
function "StrongAuth" not defined

### ISSUE THREAD

**Issue by Vanhecke** [gophish/gophish#408]
This error is occurring when the link in an email is clicked.
The browser either shows an error or gets a 404 page from gophish.

Compiled from source couple hours ago.

BTW -  I selected the "capture credentials" option.

```
2016/10/21 17:12:45 main.go:702: sql/root/go/src/github.com/gophish/gophish/models/campaign.go:1172.052171msINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[1 ccruz13@paginegialle.it 2016-10-21 17:12:45.784073895 +0200 CEST Clicked Link {"payload":{"rid":["d29cbdd7630ed7ec40ba5b4bbd2394dfe4ddd7deca3ea728c64b4a166e89c533"]},"browser":{"address":"127.0.0.1","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"}}]
2016/10/21 17:12:45 route.go:223: template: html_template:321: function "StrongAuth" not defined
2016/10/21 17:12:45 http: panic serving 127.0.0.1:50930: runtime error: invalid memory address or nil pointer dereference
goroutine 509 [running]:
net/http.(*conn).serve.func1(0xc420f31e80)
                /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x98ce20, 0xc42000c100)
                /usr/local/go/src/runtime/panic.go:458 +0x243
html/template.(*Template).escape(0x0, 0x0, 0x0)
                /usr/local/go/src/html/template/template.go:79 +0x44
html/template.(*Template).Execute(0x0, 0xe95f00, 0xc4207d20e0, 0x9b3ba0, 0xc4207ba000, 0xc420a42440, 0x40)
                /usr/local/go/src/html/template/template.go:101 +0x2f
github.com/gophish/gophish/controllers.PhishHandler(0xe9bb40, 0xc420170140, 0xc4202ae5a0)
                /root/go/src/github.com/gophish/gophish/controllers/route.go:243 +0x9d0
net/http.HandlerFunc.ServeHTTP(0xa5a070, 0xe9bb40, 0xc420170140, 0xc4202ae5a0)
                /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200160f0, 0xe9bb40, 0xc420170140, 0xc4202ae5a0)
                /root/go/src/github.com/gorilla/mux/mux.go:114 +0x10d
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0x7fed7435d978, 0xc420c90600, 0xc420702690)
                /root/go/src/github.com/NYTimes/gziphandler/gzip.go:167 +0x159
net/http.HandlerFunc.ServeHTTP(0xc4201ae500, 0x7fed7435d978, 0xc420c90600, 0xc420702690)
                /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xe97580, 0xc420028010, 0xe986c0, 0xc4201ae500, 0xe9c0c0, 0xc420c88000, 0xc420702690)
                /root/go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc4201ae540, 0xe9c0c0, 0xc420c88000, 0xc420702690)
                <autogenerated>:15 +0x8b
net/http.serverHandler.ServeHTTP(0xc4201b8380, 0xe9c0c0, 0xc420c88000, 0xc420702690)
                /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420f31e80, 0xe9c8c0, 0xc420293100)
                /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
                /usr/local/go/src/net/http/server.go:2293 +0x44d

**Comment by jordan-wright** [comment]
Hey @Vanhecke - chances are, there is some Javascript in your landing page HTML that uses the ```{{}}``` syntax. This conflicts with the gophish syntax, where it's trying to find/replace template variables and functions.

My recommendation would be to remove those instances of the ```{{{}}``` syntax from your javsascript if they are not needed.

Let me know if this helps resolve the issue!

**Comment by jordan-wright** [comment]
Hey @Vanhecke - just wanted to check in, did that fix the issue for you?

**Comment by Vanhecke** [comment]
@jordan-wright 
This was the issue, the website that I cloned used the {{ }} templating too.
