### ISSUE TITLE
GoPhish Crashing on Login

### ISSUE THREAD

**Issue by recrudesce** [gophish/gophish#509]
Had a previous install of Gophish.  Decided to update it.  Moved entire go src folder to make sure it downloaded the newest dependencies.  go build generated binary, copied over existing config.json and gophish.db from previous working install.  Started server, hit login page, logged in, and got this:

```
ubuntu@ip-172-31-15-206:~/go/src/github.com/gophish/gophish$ sudo ./gophish 
 2017/01/09 09:36:24 models.go:98: no valid version found
no valid version found
 2017/01/09 09:36:24 gophish.go:83: Starting phishing server at http://0.0.0.0:80
 2017/01/09 09:36:24 worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
 2017/01/09 09:36:24 gophish.go:66: Starting admin server at https://0.0.0.0:3333
x.x.x.x - - [09/Jan/2017:09:36:28 +0000] "GET /login HTTP/2.0" 200 1049 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.28 Safari/537.36"
x.x.x.x - - [09/Jan/2017:09:36:28 +0000] "GET /images/logo_inv_small.png HTTP/2.0" 200 1146 "https://domain:3333/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.28 Safari/537.36"
x.x.x.x - - [09/Jan/2017:09:36:28 +0000] "GET /images/logo_purple.png HTTP/2.0" 200 4690 "https://domain:3333/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.28 Safari/537.36"
x.x.x.x - - [09/Jan/2017:09:36:28 +0000] "GET /css/dist/gophish.css HTTP/2.0" 200 46849 "https://domain:3333/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.28 Safari/537.36"
x.x.x.x - - [09/Jan/2017:09:36:28 +0000] "GET /js/dist/vendor.min.js HTTP/2.0" 200 218971 "https://domain:3333/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.28 Safari/537.36"
2017/01/09 09:36:33 http2: panic serving x.x.x.x:54149: runtime error: invalid memory address or nil pointer dereference
goroutine 32 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc8202f9f4f, 0xc8202cf400, 0xc820028148)
        /usr/lib/go-1.6/src/net/http/h2_bundle.go:4050 +0xbc
panic(0xb185e0, 0xc82000a0f0)
        /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc8202e2470)
        /home/ubuntu/go/src/github.com/jinzhu/gorm/main.go:699 +0x4f4
github.com/jinzhu/gorm.(*DB).Where(0x0, 0xa14e60, 0xc8202e2470, 0xc8202e2450, 0x1, 0x1, 0x1)
        /home/ubuntu/go/src/github.com/jinzhu/gorm/main.go:166 +0x21
github.com/gophish/gophish/models.GetUserByUsername(0xc820304789, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/src/github.com/gophish/gophish/models/user.go:39 +0x1d5
github.com/gophish/gophish/auth.Login(0xc8202b21c0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/src/github.com/gophish/gophish/auth/auth.go:46 +0x11c
github.com/gophish/gophish/controllers.Login(0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /home/ubuntu/go/src/github.com/gophish/gophish/controllers/route.go:464 +0x988
net/http.HandlerFunc.ServeHTTP(0xd093f0, 0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820262000, 0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /home/ubuntu/go/src/github.com/gorilla/mux/mux.go:114 +0x2a8
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc8202c34a0, 0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /home/ubuntu/go/src/github.com/gorilla/csrf/csrf.go:267 +0x877
net/http.(Handler).ServeHTTP-fm(0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/h2_bundle.go:3847 +0x50
net/http.HandlerFunc.ServeHTTP(0xc8202d28e0, 0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/server.go:1618 +0x3a
github.com/gophish/gophish/middleware.CSRFExceptions.func1(0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /home/ubuntu/go/src/github.com/gophish/gophish/middleware/middleware.go:27 +0x178
net/http.HandlerFunc.ServeHTTP(0xc8202d2900, 0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/server.go:1618 +0x3a
github.com/gophish/gophish/middleware.GetContext.func1(0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /home/ubuntu/go/src/github.com/gophish/gophish/middleware/middleware.go:57 +0x3c2
net/http.HandlerFunc.ServeHTTP(0xc8202d2920, 0x7f77a42ee188, 0xc8202d2bc0, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/server.go:1618 +0x3a
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0x7f77a42ee150, 0xc8202d2ba0, 0xc8202b21c0)
        /home/ubuntu/go/src/github.com/NYTimes/gziphandler/gzip.go:181 +0x169
net/http.HandlerFunc.ServeHTTP(0xc8202d2940, 0x7f77a42ee150, 0xc8202d2ba0, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/server.go:1618 +0x3a
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f77a43701c0, 0xc820028010, 0x7f77a4374ee8, 0xc8202d2940, 0x7f77a42ee000, 0xc820028148, 0xc8202b21c0)
        /home/ubuntu/go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc8202d2960, 0x7f77a42ee000, 0xc820028148, 0xc8202b21c0)
        <autogenerated>:15 +0xb4
net/http.serverHandler.ServeHTTP(0xc82027fa00, 0x7f77a42ee000, 0xc820028148, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/server.go:2081 +0x19e
net/http.initNPNRequest.ServeHTTP(0xc8202da600, 0xc82027fa00, 0x7f77a42ee000, 0xc820028148, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/server.go:2489 +0x221
net/http.(*initNPNRequest).ServeHTTP(0xc8202e32a0, 0x7f77a42ee000, 0xc820028148, 0xc8202b21c0)
        <autogenerated>:253 +0xb6
net/http.(Handler).ServeHTTP-fm(0x7f77a42ee000, 0xc820028148, 0xc8202b21c0)
        /usr/lib/go-1.6/src/net/http/h2_bundle.go:3847 +0x50
net/http.(*http2serverConn).runHandler(0xc8202cf400, 0xc820028148, 0xc8202b21c0, 0xc82015b000)
        /usr/lib/go-1.6/src/net/http/h2_bundle.go:4060 +0x9f
created by net/http.(*http2serverConn).processHeaderBlockFragment
        /usr/lib/go-1.6/src/net/http/h2_bundle.go:3853 +0x55e
```

Updated to the latest golang version and libraries, but it still happens :(  Old binary still functions perfectly well, this error only happens with newly build binaries :(

**Comment by S0larflare** [comment]
I suspect the problem is your config.json file.

I think, when mysql support was added, the migrations path was altered. If you are using a config.json file from before that point it will try looking for a migration in a place which is no longer valid. 

Your config.json should contain your "admin_server" details, the "phish_server" details and then finally these 3 lines:

        "db_name" : "sqlite3",
        "db_path" : "gophish.db",
        "migrations_prefix" : "db/db_"


The db_name may be mysql, if that is what you want to use, but the default would be sqlite3. If this is fixed, the migrations path should be correct and should allow the database to be added to correctly.

**Comment by recrudesce** [comment]
You are a god amongst men.  That's exactly what the problem was.

All working now, thanks S0larflare :)

**Comment by jordan-wright** [comment]
Yep! Definitely a config issue. Excellent call, @S0larflare!
