### ISSUE TITLE
gophish crashing after admin login

### ISSUE THREAD

**Issue by RyanGandrud** [gophish/gophish#563]
Looks like gophish is crashing after entering the valid admin username and password on the 3333 port. Appears to be referencing an out of bounds memory address. I had no issues with v0.2 binary of gophish. Running a fully up to date Kali2 rolling OS with the latest Linux 64 v0.3 binary download. Below is the full output during the crash:

```
root@kali:/opt/gophish-v0.3-linux-64bit# ./gophish
 2017/03/15 14:49:52 worker.go:36: Background Worker Started Successfully - Waiting for Campaigns
 2017/03/15 14:49:52 models.go:98: no valid version found
no valid version found
 2017/03/15 14:49:52 gophish.go:66: Starting admin server at https://192.168.1.1:3333
 2017/03/15 14:49:52 gophish.go:83: Starting phishing server at http://0.0.0.0:80
2017/03/15 14:49:54 http2: server: error reading preface from client 192.168.1.1:62174: remote error: tls: unknown certificate authority
192.168.1.2 - - [15/Mar/2017:14:49:57 -0500] "GET /login HTTP/2.0" 200 1061 "" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
192.168.1.2 - - [15/Mar/2017:14:49:57 -0500] "GET /images/logo_inv_small.png HTTP/2.0" 200 1146 "https://192.168.1.1:3333/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
192.168.1.2 - - [15/Mar/2017:14:49:57 -0500] "GET /images/logo_purple.png HTTP/2.0" 200 4735 "https://192.168.1.1:3333/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
192.168.1.2 - - [15/Mar/2017:14:49:57 -0500] "GET /docs-assets/ico/favicon.png HTTP/2.0" 404 43 "" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
192.168.1.2 - - [15/Mar/2017:14:49:57 -0500] "GET /css/dist/gophish.css HTTP/2.0" 200 50138 "https://192.168.1.1:3333/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
192.168.1.2 - - [15/Mar/2017:14:49:57 -0500] "GET /js/dist/vendor.min.js HTTP/2.0" 200 225274 "https://192.168.1.1:3333/login" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"

2017/03/15 14:50:01 http2: panic serving 192.168.1.1:62176: runtime error: invalid memory address or nil pointer dereference
goroutine 184 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc42000e148, 0xc42028ffaf, 0xc420240e00)
        /usr/local/go/src/net/http/h2_bundle.go:4592 +0x190
panic(0x9eaba0, 0xf0c150)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc42028f2c0)
        /go/src/github.com/jinzhu/gorm/main.go:699 +0x76
github.com/jinzhu/gorm.(*DB).Where(0x0, 0x9bebc0, 0xc42010cf80, 0xc42010cf50, 0x1, 0x1, 0xa770c9)
        /go/src/github.com/jinzhu/gorm/main.go:166 +0x2b
github.com/gophish/gophish/models.GetUserByUsername(0xc4200d21b9, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420146a50, ...)
        /go/src/github.com/gophish/gophish/models/user.go:39 +0x1bc
github.com/gophish/gophish/auth.Login(0xc420131100, 0x9bebc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf25920, ...)
        /go/src/github.com/gophish/gophish/auth/auth.go:46 +0xf5
github.com/gophish/gophish/controllers.Login(0xf238e0, 0xc420134ea0, 0xc420131100)
        /go/src/github.com/gophish/gophish/controllers/route.go:466 +0x191
net/http.HandlerFunc.ServeHTTP(0xa98fc0, 0xf238e0, 0xc420134ea0, 0xc420131100)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420177bd0, 0xf238e0, 0xc420134ea0, 0xc420131100)
        /go/src/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc42025bf40, 0xf238e0, 0xc420134ea0, 0xc420130f00)
        /go/src/github.com/gorilla/csrf/csrf.go:267 +0x32d
net/http.(Handler).ServeHTTP-fm(0xf238e0, 0xc420134ea0, 0xc420130c00)
        /usr/local/go/src/net/http/h2_bundle.go:4319 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc4202617a0, 0xf238e0, 0xc420134ea0, 0xc420130c00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gophish/gophish/middleware.CSRFExceptions.func1(0xf238e0, 0xc420134ea0, 0xc420130c00)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:27 +0xc4
net/http.HandlerFunc.ServeHTTP(0xc4202617c0, 0xf238e0, 0xc420134ea0, 0xc420130c00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gophish/gophish/middleware.GetContext.func1(0xf238e0, 0xc420134ea0, 0xc420130c00)
        /go/src/github.com/gophish/gophish/middleware/middleware.go:57 +0x295
net/http.HandlerFunc.ServeHTTP(0xc4202617e0, 0xf238e0, 0xc420134ea0, 0xc420130b00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/NYTimes/gziphandler.NewGzipLevelHandler.func1.1(0x7f89f132a158, 0xc420134e80, 0xc420130b00)
        /go/src/github.com/NYTimes/gziphandler/gzip.go:181 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc420261800, 0x7f89f132a158, 0xc420134e80, 0xc420130b00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xf1eda0, 0xc42000e018, 0xf1ff20, 0xc420261800, 0xf23de0, 0xc42000e148, 0xc420130b00)
        /go/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc420261860, 0xf23de0, 0xc42000e148, 0xc420130b00)
        <autogenerated>:9 +0x86
net/http.serverHandler.ServeHTTP(0xc42007adc0, 0xf23de0, 0xc42000e148, 0xc420130b00)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.initNPNRequest.ServeHTTP(0xc4202a8e00, 0xc42007adc0, 0xf23de0, 0xc42000e148, 0xc420130b00)
        /usr/local/go/src/net/http/server.go:3088 +0x93
net/http.(*initNPNRequest).ServeHTTP(0xc4202a29f0, 0xf23de0, 0xc42000e148, 0xc420130b00)
        <autogenerated>:312 +0x74
net/http.(Handler).ServeHTTP-fm(0xf23de0, 0xc42000e148, 0xc420130b00)
        /usr/local/go/src/net/http/h2_bundle.go:4319 +0x4d
net/http.(*http2serverConn).runHandler(0xc420240e00, 0xc42000e148, 0xc420130b00, 0xc420134e20)
        /usr/local/go/src/net/http/h2_bundle.go:4599 +0x89
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:4331 +0x4ac
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x72c056]

goroutine 20 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc4205096e0)
        /go/src/github.com/jinzhu/gorm/main.go:699 +0x76
github.com/jinzhu/gorm.(*DB).Where(0x0, 0x9bebc0, 0xc4200e6230, 0xc4200e6220, 0x1, 0x1, 0xc4201c20a0)
        /go/src/github.com/jinzhu/gorm/main.go:166 +0x2b
github.com/gophish/gophish/models.GetQueuedCampaigns(0xed05b921c, 0xc42697670f, 0xf4c320, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/gophish/gophish/models/campaign.go:335 +0x189
github.com/gophish/gophish/worker.(*Worker).Start(0xf69360)
        /go/src/github.com/gophish/gophish/worker/worker.go:38 +0x196
created by github.com/gophish/gophish/controllers.init.1
        /go/src/github.com/gophish/gophish/controllers/api.go:31 +0x67
```
Let me know if I can provide any additional information to help troubleshoot this issue. Thank you for your hard work!

**Comment by jordan-wright** [comment]
Does the config look correct with regards to the database connection? I'd recommend using the latest version of the config if you aren't already.

**Comment by RyanGandrud** [comment]
Looks like the db config got mangled when I merged it with my old config. That was the problem. 

Thanks Jordan for the quick response!

**Comment by serpunja** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/24878620/26728381/b404c6de-47b2-11e7-9fa7-b70beea9d2f2.png)


Please help.

**Comment by jordan-wright** [comment]
This is because you're using the generated self signed certificates. Just click through the error and it should work.
