### ISSUE TITLE
502 Bad Gateway | BUG

### ISSUE THREAD

**Issue by ARiITRrIX** [gophish/gophish#847]
Hey I have a problem with my gophish. I would like to phish a samsung account. My first step was I save the landing page only html. After that I looking how it looks. It load normal and looks like the offiical Samsung Account signin. After I changed something in my language and done. I press command and A and Command and C. I paste that in to the Landing page and there it shows the same like opened in my firefox. 

Normally gophish works great but here it is buggy.

I use lt-win.exe (localtunnel me) for windows.

MY BUG is after I got the email I clicked the link it not load samsung signin (myphishwebsite) rather 

but it is my URL. in the line at the top.

What was happen ? And how I can fix it ?.

I hope someone can help me if you know more information please write it down below thx for all answers and solutions.

;)

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>

What version of Gophish are you using?: 

latest 0.4

If this question is related to email templates or landing pages not working as expected, please provide your template or landing page below:

```html  | Landing Page | Samsung account signin

<html lang="de"><head><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}.ng-animate-shim{visibility:hidden;}.ng-anchor{position:absolute;}</style><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\:form{display:block;}.ng-animate-shim{visibility:hidden;}.ng-anchor{position:absolute;}</style>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <title>Samsung | Konto-verifizierung</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
    <link rel="stylesheet" href="https://account.samsung.com/accounts/v1/resources/js/common/angular-block-ui/angular-block-ui.min.css">
    <link rel="stylesheet" type="text/css" href="https://account.samsung.com/accounts/v1/resources/css/v2/angular-material.css?20171103075814">
    <link rel="stylesheet" type="text/css" href="https://account.samsung.com/accounts/v1/resources/css/v2/iam-default.css?20171103075814">
    
    <link type="image/x-icon" rel="shortcut icon" href="https://account.samsung.com/favicon.ico?20171103075814">

</head>
    
    <body class="iam-signinUI ng-scope block-ui block-ui-anim-fade" data-ng-controller="cmmController as cmm" data-ng-style="bgStyle" block-ui="main" aria-busy="false" style="background-color: rgb(255, 255, 255);">
    <!-- iam-wrapper -->
    <div class="iam-wrapper">
        
    <header class="iam-header"><h1>Samsung account </h1></header> 
        <main class="iam-main ng-scope" data-ng-controller="signInController as vm">
            <!-- iam-main-inner -->
            <div class="iam-main-inner">
                <!-- contents -->
                <div class="iam-contents">
                    <h2>Samsung Konto </h2>
                    <!-- forms-->
                    <div class="iam-forms">
                        <form novalidate="" class="ng-pristine ng-valid ng-valid-email ng-valid-maxlength">
                            <fieldset>
                                <legend>Account Samsung login</legend>
                                <!-- user -->
                                <div class="iam-input-container">
                                    
                                    <input class="inputtext _55r1 inputtext _1kbt inputtext _1kbt" name="email" id="email" tabindex="1" placeholder="E-Mail-Adresse" value="" autofocus="1" aria-label="E-Mail-Adresse" type="text">
                                    <div class="error-msg">
                                        <div data-ng-show="((err.iptLgnPlnPD || err.iptLgnPlnID) &amp;&amp; err.code == '01')" id="" class="ng-hide">Bitte geben Sie eine ID ein.</div>
                                    </div>
                                </div>
                                <div class="iam-input-container  ">
                                    
                                    <input class="inputtext _55r1 inputtext _1kbt inputtext _1kbt" name="pass" id="pass" tabindex="1" placeholder="Passwort" aria-label="Passwort" type="password">
                                    <div class="error-msg">
                                        <div data-ng-show="((err.iptLgnPlnPD || err.iptLgnPlnID) &amp;&amp; err.code == '02')" id="" class="ng-hide">Bitte geben Sie ein Passwort ein</div>
                                        <div data-ng-show="((err.iptLgnPlnPD || err.iptLgnPlnID) &amp;&amp; err.code == '03')" id="" class="ng-hide">Geben Sie bitte die ID und das Passwort ein.</div>
                                        <div data-ng-show="((err.iptLgnPlnPD || err.iptLgnPlnID) &amp;&amp; err.code == '05')" id="" class="ng-hide">Erlauben Sie in den Einstellungen Ihres Browsers, dass Webseiten Cookie-Daten speichern und lesen dürfen.</div>
                                        <div data-ng-show="((err.iptLgnPlnPD || err.iptLgnPlnID) &amp;&amp; err.code == '99')" id="" class="ng-hide"><div data-ng-bind="err.message | trusted" class="ng-binding"></div></div>
                                    </div>
                                </div>
                                
                                <div class="iam-signIn-button"><button class="iam-button iam-primary" id="signInButton" data-ng-click="signIn()" type="button">Verifizieren</button></div>
                            </fieldset>
                        </form>
                    </div>
                    <!-- //forms -->
                    <div class="iam-signIn-link"><a href="#" data-ng-click="findInfo()">E-Mail-Adresse oder Passwort vergessen?</a> <span class="break">oder</span> <a href="#" data-ng-click="signUp()">Registrieren Sie sich hier</a></div>
                    <button type="button" class="btn-close" data-ng-click="btnGoBack();">go back</button>
                </div>
                <!-- //contents -->
            </div>
            <!-- //.iam-main-inner -->
        </main>
        
        <!-- footer -->
        <footer class="iam-footer" role="contentinfo">
            <div class="iam-footer-row">
                
                    <div class="iam-footer-inner">
                        <div class="iam-footer-goto"><a href="http://www.samsung.com/de/">Go to service</a></div>
                    </div>
                
            </div>
            <div class="iam-footer-row">
                <div class="iam-footer-inner">
                    <div class="iam-footer-links">
                        <a href="https://account.samsung.com/accounts/v1/accounts/v1/b0cc6a5cda133d32360a9d6ddfd5ec01/termsDetail?closeBtnYN=N" target="_blank">Nutzungsbedingungen</a>
                        <!-- 
                        
                            
                            
                                <a href="https://account.samsung.com/accounts/v1/accounts/v1/b0cc6a5cda133d32360a9d6ddfd5ec01/termsPP?closeBtnYN=N" target="_blank">Samsung Hinweise zum Datenschutz</a>
                            
                        
                         -->
                        <a href="https://account.samsung.com/accounts/v1/accounts/v1/b0cc6a5cda133d32360a9d6ddfd5ec01/termsFooterPP?closeBtnYN=N" target="_blank">Samsung Hinweise zum Datenschutz</a>
                        <a href="https://account.samsung.com/accounts/v1/accounts/v1/b0cc6a5cda133d32360a9d6ddfd5ec01/contactUs" target="_blank">Kontaktiere uns</a>
                    </div>
                    <address class="iam-footer-address">© Samsung Electronics Co., Ltd.</address>	
                </div>
            </div>
        </footer>
        <!-- //footer -->
    </div>
    <!-- //wrap-->
    
    
    
    <div block-ui-container="" class="block-ui-container ng-scope"><div class="block-ui-overlay"></div><div class="block-ui-message-container" aria-live="assertive" aria-atomic="true"><div class="block-ui-message ng-binding" ng-class="$_blockUiMessageClass">{{ state.message }}</div></div></div><div block-ui-container="" class="block-ui-container ng-scope"><div class="block-ui-overlay"></div><div class="block-ui-message-container" aria-live="assertive" aria-atomic="true"><div class="block-ui-message ng-binding" ng-class="$_blockUiMessageClass">{{ state.message }}</div></div></div></body></html>


<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>

```
TERMINAL OUTPUT | 

```
 2017/11/19 18:32:27 main.go:740: sql/go/src/github.com/gophish/gophish/models/campaign.go:1440sINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[7 fn49d@vmani.com 2017-11-19 17:32:27.5873478 +0000 UTC Email Opened {"payload":{"rid":["laofD04"]},"browser":{"address":"MYIP","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"}}] 1
127.0.0.1 - - [19/Nov/2017:18:32:27 +0100] "GET /track?rid=laofD04 HTTP/1.1" 200 95 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"
 2017/11/19 18:32:29 main.go:740: sql/go/src/github.com/gophish/gophish/models/campaign.go:1440sINSERT INTO "events" ("campaign_id","email","time","message","details") VALUES (?,?,?,?,?)[7 fn49d@vmani.com 2017-11-19 17:32:29.1162847 +0000 UTC Clicked Link {"payload":{"rid":["laofD04"]},"browser":{"address":"78.35.112.171","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"}}] 1
 2017/11/19 18:32:29 phish.go:119: template: html_template:477: function "state" not defined
2017/11/19 18:32:29 http: panic serving 127.0.0.1:50748: runtime error: invalid memory address or nil pointer dereference
goroutine 8822 [running]:
net/http.(*conn).serve.func1(0xc0421743c0)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0x9c46a0, 0xe09320)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
html/template.(*Template).escape(0x0, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:94 +0x3f
html/template.(*Template).Execute(0x0, 0xddad80, 0xc04214c0e0, 0x9f2f20, 0xc0434723c0, 0xc042e81130, 0x7)
        /usr/local/go/src/html/template/template.go:117 +0x36
github.com/gophish/gophish/controllers.PhishHandler(0xde1480, 0xc043116300, 0xc04311e300)
        /go/src/github.com/gophish/gophish/controllers/phish.go:139 +0xbfa
net/http.HandlerFunc.ServeHTTP(0xa830e8, 0xde1480, 0xc043116300, 0xc04311eb00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc04223d560, 0xde1480, 0xc043116300, 0xc04311eb00)
        /go/src/github.com/gorilla/mux/mux.go:133 +0x108
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x37f2548, 0xc0427e3e30, 0xc0431e0e00)
        /go/src/github.com/NYTimes/gziphandler/gzip.go:269 +0x180
net/http.HandlerFunc.ServeHTTP(0xc042242c00, 0x37f2548, 0xc0427e3e30, 0xc0431e0e00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xddc300, 0xc042064008, 0xddd400, 0xc042242c00, 0xde18c0, 0xc0425602a0, 0xc0431e0e00)
        /go/src/github.com/gorilla/handlers/handlers.go:77 +0x128
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc0422705c0, 0xde18c0, 0xc0425602a0, 0xc0431e0e00)
        <autogenerated>:9 +0x8d
net/http.serverHandler.ServeHTTP(0xc042240580, 0xde18c0, 0xc0425602a0, 0xc0431e0e00)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc0421743c0, 0xde2100, 0xc04211b200)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
127.0.0.1 - - [19/Nov/2017:18:32:29 +0100] "GET /favicon.ico HTTP/1.1" 404 19 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [19/Nov/2017:18:32:29 +0100] "GET /favicon.ico HTTP/1.1" 404 19 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"
```

**Comment by jordan-wright** [comment]
There's a lot going on here.

I haven't used lt-win.exe before, so I can't provide any support for that. You need to make sure that regardless of what landing page you use, connections are hitting Gophish directly. The `502 Bad Gateway` makes me think that there's some other webserver handling the connections.

In addition to this, the error you posted is regarding the `{{ state.message }}` in the HTML.  Gophish interprets this as a template value, so it breaks. You'll need to remove those `{{ key }}` values and re-save the HTML.

Hope this helps!
